[package]
name = "circuit"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.3.1"

[dev-dependencies]
cairo_test = "2.9.2"
assert_macros = "2.9.2"

[[target.starknet-contract]]
sierra = true

[scripts]
test = "snforge test"

[cairo]
sierra = true

[lib]                         # For standalone Cairo programs
sierra = true